---
name: Docker build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:

############# start setting up QEMU #############
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
############ end setting up QEMU #############

############# start setting up build kit ############
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
############ end setting up build kit #########

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker build
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: mwangikibui/docker-ci-automation:latest

############# buildkit cache ##########
          cache-from: type=gha
          cache-to: type=gha,mode=max
############ end buildkit cache ##########

########### start of platforms ###########
          platforms: linux/amd64,linux/arm64,linux/arm/v7
########## end of platforms ##########
    
