---
name: Docker build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:

############# start setting up QEMU #############
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
############ end setting up QEMU #############

############# start setting up build kit ############
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
############ end setting up build kit #########

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

##################### docker meta start ##################
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          image: mwangikibui/docker-ci-automation
          flavor: |
            latest=false
          tags: |
            type=raw,value=04
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern=${{version}}
####################### end of docker meta ################

      
      - name: Docker build
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: mwangikibui/docker-ci-automation:latest

############# buildkit cache ##########
          cache-from: type=gha
          cache-to: type=gha,mode=max
############ end buildkit cache ##########

########### start of platforms ###########
          platforms: linux/amd64,linux/arm64,linux/arm/v7
########## end of platforms ##########
    
